import turtle
pete= turtle.Turtle()
pete.shape("turtle")
pete.forward(200)
pete.left(810)
pete.right(90)
pete.back(100)
pete.reset()
pete.color("blue")
pete.forward(100)
pete.color("red")
pete.left(90)
pete.forward(100)
pete.color("cyan")
pete.forward(100)
pete.reset()
pete.circle(100)
pete.circle(200)
pete.circle(-100)
pete.up()
pete.forward(200)
pete.down()
pete.back(100)
turtle.done()
